# Generated by Django 2.1.4 on 2020-11-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifas', '0013_rifa_e_ganhador'),
    ]

    operations = [
        migrations.CreateModel(
            name='avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('nome', models.TextField()),
                ('texto', models.TextField()),
            ],
        ),
    ]
